version: "3"

services:
  mercury-parser:
    image: wangqiru/mercury-parser-api
    volumes:
    - ./Mods/routes.js:/app/routes.js
    - ./Mods/index.js:/app/index.js
    expose:
      - "3000"
  nginx-load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mercury-parser
    ports:
      - "4000:4000"


